### ISSUE TITLE
[Feature request] Using with specific attribute

### ISSUE THREAD

**Issue by 573** [nicknovitski/nix-develop#4]
I have
```yaml
    matrix:
        nix-command:
          - develop .#cljShell --impure --accept-flake-config --command clj --version
          - develop .#rustyShell --impure --accept-flake-config --command rustc --version
          - develop .#rustShell --impure --accept-flake-config --command rustc --version
          - develop .#yaocaml --impure --accept-flake-config --command ocaml --version
          - develop .#agda --impure --accept-flake-config --command ghci --version
          - develop .#haskell --impure --accept-flake-config --command ghci --version
```
Is that translatable to `nix-develop` syntax i. e. not using the default `.#` ?

Right now I only see
```
- uses: nicknovitski/nix-develop@v1
  with:
    arguments: .#cljShell --impure --accept-flake-config
- run: clj --version
```
but that alone wouldn't help [DRY](https://w.wiki/JAp) either.

**Comment by nicknovitski** [comment]
Ohhh, using a matrix?  Cool!  I'd try splitting apart those commands into just the parts which vary, and use `includes:`, maybe like this:
```yaml
jobs:
  nix-checks:
      matrix:
        includes:
          - shell: cljShell
             command: clj --version
          - shell: rustyShell
             command: rustc --version
          - shell: rustShell
             command: rustc --version
          # ...etc
    steps:
      - uses: actions/checkout@v4
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ./#${{ matrix.shell }} --impure --accept-flake-config
      - run: ${{ inputs.command }}
```

**Comment by nicknovitski** [comment]
But if you only ever need to run a single command in a given shell, that's actually great, and you're past the point of needing this action. I personally think it's a big improvement to move commands from multiple CI yaml steps into single locally executable scripts.

For example, here's a refactor that I would approve on a project

```yaml
# before
      - uses: nicknovitski/nix-develop@v1
      - run: cargo fmt --check
      - run: cargo-deny check
      - run: eclint \
               -exclude "Cargo.lock"
      - run: codespell \
              --skip target,.git \
              --ignore-words-list crate
# after
      - run: nix develop --command ./run-checks.sh # bash script which calls those other things
```

I should probably add that advice to the readme...

Does any of this help you?
